language: go

go:
    - 1.2.2
    - 1.5
    - tip

notifications:
    email: 
        recipients:
            secure: secure: "jTIahWktjY9Sc3CVie4UGkNZxCpzUqlc7kuhrcOQ5CmjrGnv/JafiaCC31W8Vekq/AieMr8+dTe9KEHDPpOacAEKTiPg9SiSsGtj+vvSC9KuIcQ/4dNmKxb5/h9Dc5KaU02b1AzCuABhrVgBDTGWxl5pqtxN72MaffBcFqAzdRDXzfycIalu39gVWK7+PzIvCvcPJjt41qbHiOuNT1wIzkocia5er86f5SSPylaNxLokevqhFTrgVhfyTzdk6LAOi7A2ifkv7cOCkmugmyggCaVMVQMD0AR56Cym8GvkckmV2rEAbaa3RuVPfWg/K7B1Jl0koWc5cdcuPN4HZwbUJAu0vsJdWZ6r44She/8IoTH9YtxlVy9yf/tP8qT5L0OMcDA8BQReBJZR6SZ/Bw2v+wg+AJ26n/weKOO7G/nGRJa3JQ8CiBEcr32zPF/bNeS90Vb6HhLT8o/SMgl4R0LHQpDsKua0Jgd7N8ClGdx5xErho0t48dX0kzOdZO5UpT22KWKChzQMjwW2weCsF977f8QIjCUYjf+35nveAklz9rMS7BO6PeNi6aR5hlrdrflsjCRzsb106fDETMtXsO+rgirZt/D8K0i6Yo78Ry5Oqf2NM2QjGvkaKYbugpnjspYSSOSajpo9dGlUCbBa/QD5vvTTfwy7CLkmwkLOPkkZ3gc="
        on_success: never
        on_failure: always